// Generated by github.com/axisrobo/peiravela/backend/cmd/gen-client.
// DO NOT EDIT. Source of truth: contracts/schemas/*.json and the control-plane API.

class PeiravelaClient {
  constructor(baseURL = "", headers = {}) {
    this.baseURL = baseURL;
    this.headers = headers;
  }

  async fetch(input, init = {}) {
    const res = await fetch(this.baseURL + input, Object.assign({ headers: this.headers }, init));
    const text = await res.text();
    let parsed;
    try { parsed = JSON.parse(text); } catch { parsed = text; }
    if (!res.ok) {
      throw new Error((parsed && parsed.error) || res.status + " " + res.statusText);
    }
    return parsed;
  }

  health() { return this.fetch("/health"); }
  providerSandboxes() { return this.fetch("/provider-sandboxes"); }
  sutAdapters() { return this.fetch("/sut-adapters"); }
  expandCatalog(req) { return this.fetch("/catalogs/expand", { method: "POST", body: JSON.stringify(req) }); }
  createSourceBinding(req) { return this.fetch("/source-bindings", { method: "POST", body: JSON.stringify(req) }); }
  listSourceBindings() { return this.fetch("/source-bindings"); }
  getSourceBinding(bindingID) { return this.fetch("/source-bindings/" + encodeURIComponent(bindingID)); }
  createWorld(req) { return this.fetch("/worlds", { method: "POST", body: JSON.stringify(req) }); }
  listWorlds() { return this.fetch("/worlds"); }
  getWorld(worldID) { return this.fetch("/worlds/" + encodeURIComponent(worldID)); }
  createExperiment(req) { return this.fetch("/experiments", { method: "POST", body: JSON.stringify(req) }); }
  listExperiments() { return this.fetch("/experiments"); }
  getExperiment(experimentID) { return this.fetch("/experiments/" + encodeURIComponent(experimentID)); }
  listRuns() { return this.fetch("/runs"); }
  getRun(runID) { return this.fetch("/runs/" + encodeURIComponent(runID)); }
  getAttempt(runID, attemptID) { return this.fetch("/runs/" + encodeURIComponent(runID) + "/attempts/" + encodeURIComponent(attemptID)); }
  compileScenario(req) { return this.fetch("/scenarios/compile", { method: "POST", body: JSON.stringify(req) }); }
  suiteRun(req) { return this.fetch("/runs/suite", { method: "POST", body: JSON.stringify(req) }); }
  matrixRun(req) { return this.fetch("/runs/matrix", { method: "POST", body: JSON.stringify(req) }); }
  retainedMatrixRun(req) { return this.fetch("/runs/retained-matrix", { method: "POST", body: JSON.stringify(req) }); }
  benchRun(req) { return this.fetch("/runs/bench", { method: "POST", body: JSON.stringify(req) }); }
  listEvidence(attemptID, artifactRoot) {
    let url = "/evidence?attempt_id=" + encodeURIComponent(attemptID);
    if (artifactRoot) url += "&artifact_root=" + encodeURIComponent(artifactRoot);
    return this.fetch(url);
  }
  getEvidence(attemptID, digest, artifactRoot) {
    let url = "/evidence/" + encodeURIComponent(attemptID) + "/" + encodeURIComponent(digest);
    if (artifactRoot) url += "?artifact_root=" + encodeURIComponent(artifactRoot);
    return this.fetch(url).then(function (text) { return new Blob([text]); });
  }
  exportEvidence(attemptID, artifactRoot) {
    let url = "/evidence/export?attempt_id=" + encodeURIComponent(attemptID);
    if (artifactRoot) url += "&artifact_root=" + encodeURIComponent(artifactRoot);
    return this.fetch(url).then(function (text) { return new Blob([text]); });
  }
  updateWorldState(worldID, req) { return this.fetch("/worlds/" + encodeURIComponent(worldID) + "/state", { method: "PATCH", body: JSON.stringify(req) }); }
  extendWorldLease(worldID, req) { return this.fetch("/worlds/" + encodeURIComponent(worldID) + "/lease", { method: "POST", body: JSON.stringify(req) }); }
  destroyWorld(worldID, req) { return this.fetch("/worlds/" + encodeURIComponent(worldID) + "/destroy", { method: "POST", body: JSON.stringify(req) }); }
  deleteWorld(worldID) { return this.fetch("/worlds/" + encodeURIComponent(worldID), { method: "DELETE" }); }
  updateExperimentState(experimentID, req) { return this.fetch("/experiments/" + encodeURIComponent(experimentID) + "/state", { method: "PATCH", body: JSON.stringify(req) }); }
  deleteExperiment(experimentID) { return this.fetch("/experiments/" + encodeURIComponent(experimentID), { method: "DELETE" }); }
  updateRunState(runID, req) { return this.fetch("/runs/" + encodeURIComponent(runID) + "/state", { method: "PATCH", body: JSON.stringify(req) }); }
  deleteRun(runID) { return this.fetch("/runs/" + encodeURIComponent(runID), { method: "DELETE" }); }
  createBranch(req) { return this.fetch("/branches", { method: "POST", body: JSON.stringify(req) }); }
  listBranches() { return this.fetch("/branches"); }
  getBranch(branchID) { return this.fetch("/branches/" + encodeURIComponent(branchID)); }
  verifyEvidence(req) { return this.fetch("/evidence/verify", { method: "POST", body: JSON.stringify(req) }); }
  listAuditEvents(limit) {
    let url = "/audit-events";
    if (limit) url += "?limit=" + encodeURIComponent(limit);
    return this.fetch(url);
  }
}

export default PeiravelaClient;
