// Generated by github.com/axisrobo/peiravela/backend/cmd/gen-client.
// DO NOT EDIT. Source of truth: contracts/schemas/*.json and the control-plane API.

export interface CounterfactualBranch {
  api_version: "peiravela/v1";
  cleanup_required: true;
  id: string;
  isolation_proof_ref: string;
  kind: "CounterfactualBranch";
  mutation_digest: string;
  namespace: string;
  root_snapshot_digest: string;
}

export interface EvidencePackage {
  api_version: "peiravela/v1";
  artifacts: { digest: string; kind: string; path: string }[];
  attempt_id: string;
  created_at: string;
  kind: "EvidencePackage";
  manifest_version: "1.0.0";
}

export interface ExperimentSourceBindingExperimentTrackBinding {
  control_catalog_digest?: string;
  evaluation_binding: { external_evaluator_required: true; judgments_owned_by_peiravela: false; oracle_digest: string };
  evidence_schema_digest: string;
  perturbation_catalog_digest: string;
  scenario_catalog_digest: string;
  seed_catalog_digest?: string;
  status: "draft" | "frozen" | "deprecated";
  track_id: string;
  world_contract_digest: string;
}

export interface ExperimentSourceBinding {
  api_version: "peiravela/v1";
  evaluation_boundary?: { external_evaluator_required: true; judgments_owned_by_peiravela: false };
  kind: "ExperimentSourceBinding";
  mapping_version: string;
  provenance: { source_uri: string; state_label: "observed" | "replayed" | "synthetic" | "simulated" | "predicted" | "derived" };
  source_digest: string;
  source_id: string;
  source_kind: "benchmark-suite" | "experiment-plan" | "scenario-catalog";
  source_revision: string;
  status: "draft" | "frozen" | "deprecated";
  tracks: ExperimentSourceBindingExperimentTrackBinding[];
}

export interface Experiment {
  api_version: "peiravela/v1";
  cleanup: "destroy-world";
  id: string;
  kind: "Experiment";
  matrix: Record<string, unknown>;
  repetitions: number;
  retry_policy: { max_attempts: number };
  root_world_ref: string;
  scenario_ref: string;
  source_binding_ref?: string;
  version: string;
}

export interface JACoBProfileDimension {
  categories: { id: string; status: "planned" | "active" | "frozen" | "deprecated"; suite_refs: string[] }[];
  id: string;
  status: "planned" | "active" | "frozen" | "deprecated";
}

export interface JACoBProfile {
  api_version: "peiravela/v1";
  evaluation_boundary: { external_evaluator_required: true; judgments_owned_by_peiravela: false };
  id: string;
  kind: "JACoBProfile";
  provenance: { source_digest: string; state_label: "observed" | "replayed" | "synthetic" | "simulated" | "predicted" | "derived" };
  quality_dimensions: JACoBProfileDimension[];
  version: string;
}

export interface RunManifest {
  api_version: "peiravela/v1";
  attempt_id: string;
  clock: string;
  created_at: string;
  dependencies: Record<string, unknown>;
  experiment_id: string;
  kind: "RunManifest";
  replaces_attempt_id?: string;
  run_id: string;
  scenario_digest: string;
  seed: number | string;
  world_digest: string;
}

export interface ScenarioProvenance {
  source_digest: string;
  state_label: "observed" | "replayed" | "synthetic" | "simulated" | "predicted" | "derived";
}

export interface Scenario {
  actors: Record<string, unknown>[];
  api_version: "peiravela/v1";
  id: string;
  invariants?: Record<string, unknown>[];
  kind: "Scenario";
  perturbations?: Record<string, unknown>[];
  provenance: ScenarioProvenance;
  steps: Record<string, unknown>[];
  version: string;
  world_ref: string;
}

export interface SecurityLabProfileDomain {
  categories: { id: string; status: "planned" | "active" | "frozen" | "deprecated"; suite_refs: string[] }[];
  id: string;
  status: "planned" | "active" | "frozen" | "deprecated";
}

export interface SecurityLabProfile {
  api_version: "peiravela/v1";
  domains: SecurityLabProfileDomain[];
  id: string;
  kind: "SecurityLabProfile";
  provenance: { source_digest: string; state_label: "observed" | "replayed" | "synthetic" | "simulated" | "predicted" | "derived" };
  safety_boundary: { production_credentials_allowed: false; public_egress_allowed: false; synthetic_or_controlled_targets_only: true };
  version: string;
}

export interface SimulationEvidence {
  api_version: "peiravela/v1";
  attempt_id: string;
  cleanup: { residual_scan_ref: string; verified: boolean };
  execution: Record<string, unknown>;
  experiment_id: string;
  inputs: Record<string, unknown>;
  integrity: Record<string, unknown>;
  kind: "SimulationEvidence";
  observations: Record<string, unknown>;
  run_id: string;
}

export interface WorldTemplateProvenance {
  source_digest: string;
  state_label: "observed" | "replayed" | "synthetic" | "simulated" | "predicted" | "derived";
}

export interface WorldTemplate {
  api_version: "peiravela/v1";
  cleanup: { residual_scan_required: true; ttl_seconds: number };
  id: string;
  kind: "WorldTemplate";
  network?: Record<string, unknown>;
  provenance: WorldTemplateProvenance;
  provider: string;
  resource_spec: Record<string, unknown>;
  topology: string;
  version: string;
}


export interface CreateWorldRequest {
  world_id: string;
  version?: string;
  provider?: string;
  topology?: string;
  world_contract_digest: string;
  lease_ttl_seconds: number;
}

export interface CleanupEvidence {
  destroyed: boolean;
  residual_scan_ref: string;
}

export interface WorldRecord {
  world_id: string;
  version: string;
  provider: string;
  topology: string;
  world_contract_digest: string;
  state: string;
  lease_expires_at: string;
  cleanup?: CleanupEvidence;
  created_at: string;
}

export interface WorldListResponse {
  worlds: WorldRecord[];
}

export interface CreateExperimentRequest {
  experiment_id: string;
  version?: string;
  source_binding_ref?: string;
}

export interface ExperimentRecord {
  experiment_id: string;
  version: string;
  source_binding_ref?: string;
  state: string;
  created_at: string;
}

export interface ExperimentListResponse {
  experiments: ExperimentRecord[];
}

export interface CreateSourceBindingRequest {
  catalog_path: string;
  source_id: string;
  source_kind: string;
  source_revision: string;
  mapping_version: string;
  evidence_schema_digest: string;
}

export interface SourceBindingRecord {
  binding_id: string;
  binding: ExperimentSourceBinding;
}

export interface SourceBindingListResponse {
  source_bindings: SourceBindingRecord[];
}

export interface ExpandCatalogRequest {
  catalog_path: string;
}

export interface PlanSummary {
  scenario_id: string;
  perturbation_id: string;
  control_id?: string;
  seed?: number;
  label?: string;
  namespace?: string;
}

export interface ExpandCatalogResponse {
  catalog_id: string;
  catalog_version: string;
  plan_count: number;
  plans: PlanSummary[];
}

export interface SuiteRunRequest {
  catalog_path: string;
  schema_path: string;
  artifact_root?: string;
  scenario_id: string;
  perturbation_id: string;
  control_id?: string;
  seed?: number;
  sandbox_provider?: string;
}

export interface MatrixRunRequest {
  catalog_path: string;
  schema_path: string;
  artifact_root?: string;
  concurrency?: number;
  seed?: number;
  sandbox_provider?: string;
}

export interface RetainedMatrixRunRequest {
  catalog_path: string;
  schema_path: string;
  artifact_root?: string;
  concurrency?: number;
  repetitions: number;
  max_retries?: number;
  seed?: number;
  sandbox_provider?: string;
}

export interface BenchRunRequest {
  catalog_path: string;
  schema_path: string;
  artifact_root?: string;
  concurrency?: number;
  repetitions: number;
  max_retries?: number;
  seed?: number;
  sandbox_provider?: string;
}

export interface ControlsAggregateRequest {
  catalog_path: string;
  artifact_root: string;
}

export interface ScenarioAggregate {
  scenario_id: string;
  attempts: number;
  with_evidence: number;
  incomplete: number;
}

export interface ControlAggregate {
  control_id: string;
  adapter: string;
  options?: Record<string, string>;
  plan_count: number;
  attempts: number;
  with_evidence: number;
  incomplete: number;
  mean_memory_bytes?: number;
  mean_cpu_millis?: number;
  mean_runtime_ms?: number;
  resource_provider?: string;
  resource_reported: boolean;
  variants?: string[];
  scenarios?: ScenarioAggregate[];
}

export interface ControlsAggregateResponse {
  catalog_id: string;
  artifact_root?: string;
  controls: ControlAggregate[];
}

export interface ResourceUsage {
  provider: string;
  cpu_millis?: number;
  memory_bytes?: number;
  measured_at: string;
}

export interface SuiteRunResponse {
  run_id: string;
  state: string;
  evidence: ArtifactRef;
  cleanup: ArtifactRef;
  resource_usage?: ResourceUsage;
}

export interface RunResult {
  scenario_id: string;
  perturbation_id: string;
  label?: string;
  attempt_id: string;
  state: string;
  evidence_digest?: string;
  cleanup_digest?: string;
  error?: string;
}

export interface RepetitionResult {
  scenario_id: string;
  perturbation_id: string;
  label?: string;
  attempt_id: string;
  state: string;
  evidence_digest?: string;
  cleanup_digest?: string;
  error?: string;
  repetition: number;
  parent_attempt_id?: string;
  started_at: string;
  ended_at: string;
}

export interface MatrixRunResponse {
  catalog_id: string;
  total: number;
  completed: number;
  failed: number;
  results: RunResult[];
}

export interface RetainedMatrixRunResponse {
  catalog_id: string;
  repetitions_requested: number;
  total_attempts: number;
  completed: number;
  failed: number;
  with_evidence: number;
  with_cleanup: number;
  results: RepetitionResult[];
}

export interface RebuiltManifest {
  attempt_id: string;
  scenario_id: string;
  perturbation_id: string;
  label: string;
  repetition: number;
  state: string;
  artifacts: ArtifactRef[];
  observations?: Record<string, string>;
}

export interface BenchReport {
  catalog_id: string;
  repetitions: number;
  total_attempts: number;
  completed: number;
  failed: number;
  with_evidence: number;
  with_cleanup: number;
  rebuilt_manifests: RebuiltManifest[];
  replay_verification: string;
  completeness_check: string;
}

export interface CompileScenarioRequest {
  schema_path: string;
  source: string;
}

export interface CompiledScenario {
  source_digest: string;
  ir_digest: string;
  ir: unknown;
}

export interface ArtifactRef {
  kind: string;
  ref: string;
  digest: string;
}

export interface AttemptRecord {
  run_id: string;
  attempt_id: string;
  replaces_attempt_id?: string;
  state: string;
  artifacts: ArtifactRef[];
  created_at: string;
}

export interface RunRecord {
  run_id: string;
  state: string;
  created_at: string;
  attempts: AttemptRecord[];
}

export interface RunListResponse {
  runs: RunRecord[];
}

export interface EvidenceArtifact {
  kind: string;
  digest: string;
}

export interface EvidenceListResponse {
  artifact_root: string;
  attempt_id: string;
  digests: string[];
  artifacts: EvidenceArtifact[];
}

export interface UpdateWorldStateRequest {
  state: string;
}

export interface ExtendWorldLeaseRequest {
  lease_expires_at: string;
}

export interface DestroyWorldRequest {
  residual_scan_ref: string;
}

export interface UpdateExperimentStateRequest {
  state: string;
}

export interface UpdateRunStateRequest {
  state: string;
}

export interface CreateBranchRequest {
  branch_id: string;
  root_snapshot_digest: string;
  mutation_digest: string;
  namespace?: string;
  isolation_proof_ref: string;
  cleanup_required?: boolean;
  snapshot_digest: string;
}

export interface BranchRecord {
  branch_id: string;
  root_snapshot_digest: string;
  mutation_digest: string;
  namespace: string;
  isolation_proof_ref: string;
  cleanup_required: boolean;
  snapshot_digest: string;
  created_at: string;
}

export interface BranchListResponse {
  branches: BranchRecord[];
}

export interface VerifyEvidenceRequest {
  artifact_root?: string;
  attempt_id: string;
  digest: string;
}

export interface VerifyEvidenceResponse {
  attempt_id: string;
  digest: string;
  verified: boolean;
}

export interface AuditEvent {
  timestamp: string;
  actor: string;
  tenant: string;
  method: string;
  path: string;
  status: number;
  duration_ms: number;
  error?: string;
}

export class PeiravelaClient {
  baseURL: string;
  headers: Record<string, string>;

  constructor(baseURL = "", headers: Record<string, string> = {}) {
    this.baseURL = baseURL;
    this.headers = headers;
  }

  private async fetch(input: string, init: RequestInit = {}): Promise<any> {
    const res = await fetch(this.baseURL + input, Object.assign({ headers: this.headers }, init));
    const text = await res.text();
    let parsed: any;
    try { parsed = JSON.parse(text); } catch { parsed = text; }
    if (!res.ok) {
      throw new Error((parsed && parsed.error) || res.status + " " + res.statusText);
    }
    return parsed;
  }

  health(): Promise<{ status: string; version: string; store: string; tenant_id?: string; quotas?: Record<string, number> }> { return this.fetch("/health"); }
  providerSandboxes(): Promise<{ providers: unknown[] }> { return this.fetch("/provider-sandboxes"); }
  sutAdapters(): Promise<{ adapters: unknown[] }> { return this.fetch("/sut-adapters"); }
  expandCatalog(req: ExpandCatalogRequest): Promise<ExpandCatalogResponse> { return this.fetch("/catalogs/expand", { method: "POST", body: JSON.stringify(req) }); }
  createSourceBinding(req: CreateSourceBindingRequest): Promise<SourceBindingRecord> { return this.fetch("/source-bindings", { method: "POST", body: JSON.stringify(req) }); }
  listSourceBindings(): Promise<SourceBindingListResponse> { return this.fetch("/source-bindings"); }
  getSourceBinding(bindingID: string): Promise<SourceBindingRecord> { return this.fetch("/source-bindings/" + encodeURIComponent(bindingID)); }
  createWorld(req: CreateWorldRequest): Promise<WorldRecord> { return this.fetch("/worlds", { method: "POST", body: JSON.stringify(req) }); }
  listWorlds(): Promise<WorldListResponse> { return this.fetch("/worlds"); }
  getWorld(worldID: string): Promise<WorldRecord> { return this.fetch("/worlds/" + encodeURIComponent(worldID)); }
  createExperiment(req: CreateExperimentRequest): Promise<ExperimentRecord> { return this.fetch("/experiments", { method: "POST", body: JSON.stringify(req) }); }
  listExperiments(): Promise<ExperimentListResponse> { return this.fetch("/experiments"); }
  getExperiment(experimentID: string): Promise<ExperimentRecord> { return this.fetch("/experiments/" + encodeURIComponent(experimentID)); }
  listRuns(): Promise<RunListResponse> { return this.fetch("/runs"); }
  getRun(runID: string): Promise<RunRecord> { return this.fetch("/runs/" + encodeURIComponent(runID)); }
  getAttempt(runID: string, attemptID: string): Promise<AttemptRecord> { return this.fetch("/runs/" + encodeURIComponent(runID) + "/attempts/" + encodeURIComponent(attemptID)); }
  compileScenario(req: CompileScenarioRequest): Promise<CompiledScenario> { return this.fetch("/scenarios/compile", { method: "POST", body: JSON.stringify(req) }); }
  suiteRun(req: SuiteRunRequest): Promise<SuiteRunResponse> { return this.fetch("/runs/suite", { method: "POST", body: JSON.stringify(req) }); }
  matrixRun(req: MatrixRunRequest): Promise<MatrixRunResponse> { return this.fetch("/runs/matrix", { method: "POST", body: JSON.stringify(req) }); }
  retainedMatrixRun(req: RetainedMatrixRunRequest): Promise<RetainedMatrixRunResponse> { return this.fetch("/runs/retained-matrix", { method: "POST", body: JSON.stringify(req) }); }
  benchRun(req: BenchRunRequest): Promise<BenchReport> { return this.fetch("/runs/bench", { method: "POST", body: JSON.stringify(req) }); }
  listEvidence(attemptID: string, artifactRoot?: string): Promise<EvidenceListResponse> {
    let url = "/evidence?attempt_id=" + encodeURIComponent(attemptID);
    if (artifactRoot) url += "&artifact_root=" + encodeURIComponent(artifactRoot);
    return this.fetch(url);
  }
  getEvidence(attemptID: string, digest: string, artifactRoot?: string): Promise<Blob> {
    let url = "/evidence/" + encodeURIComponent(attemptID) + "/" + encodeURIComponent(digest);
    if (artifactRoot) url += "?artifact_root=" + encodeURIComponent(artifactRoot);
    return this.fetch(url).then(function (text: any): Blob { return new Blob([text]); });
  }
  exportEvidence(attemptID: string, artifactRoot?: string): Promise<Blob> {
    let url = "/evidence/export?attempt_id=" + encodeURIComponent(attemptID);
    if (artifactRoot) url += "&artifact_root=" + encodeURIComponent(artifactRoot);
    return this.fetch(url).then(function (text: any): Blob { return new Blob([text]); });
  }
  updateWorldState(worldID: string, req: UpdateWorldStateRequest): Promise<WorldRecord> { return this.fetch("/worlds/" + encodeURIComponent(worldID) + "/state", { method: "PATCH", body: JSON.stringify(req) }); }
  extendWorldLease(worldID: string, req: ExtendWorldLeaseRequest): Promise<WorldRecord> { return this.fetch("/worlds/" + encodeURIComponent(worldID) + "/lease", { method: "POST", body: JSON.stringify(req) }); }
  destroyWorld(worldID: string, req: DestroyWorldRequest): Promise<WorldRecord> { return this.fetch("/worlds/" + encodeURIComponent(worldID) + "/destroy", { method: "POST", body: JSON.stringify(req) }); }
  deleteWorld(worldID: string): Promise<unknown> { return this.fetch("/worlds/" + encodeURIComponent(worldID), { method: "DELETE" }); }
  updateExperimentState(experimentID: string, req: UpdateExperimentStateRequest): Promise<ExperimentRecord> { return this.fetch("/experiments/" + encodeURIComponent(experimentID) + "/state", { method: "PATCH", body: JSON.stringify(req) }); }
  deleteExperiment(experimentID: string): Promise<unknown> { return this.fetch("/experiments/" + encodeURIComponent(experimentID), { method: "DELETE" }); }
  updateRunState(runID: string, req: UpdateRunStateRequest): Promise<RunRecord> { return this.fetch("/runs/" + encodeURIComponent(runID) + "/state", { method: "PATCH", body: JSON.stringify(req) }); }
  deleteRun(runID: string): Promise<unknown> { return this.fetch("/runs/" + encodeURIComponent(runID), { method: "DELETE" }); }
  createBranch(req: CreateBranchRequest): Promise<BranchRecord> { return this.fetch("/branches", { method: "POST", body: JSON.stringify(req) }); }
  listBranches(): Promise<BranchListResponse> { return this.fetch("/branches"); }
  getBranch(branchID: string): Promise<BranchRecord> { return this.fetch("/branches/" + encodeURIComponent(branchID)); }
  verifyEvidence(req: VerifyEvidenceRequest): Promise<VerifyEvidenceResponse> { return this.fetch("/evidence/verify", { method: "POST", body: JSON.stringify(req) }); }
  listAuditEvents(limit?: number): Promise<{ events: AuditEvent[] }> {
    let url = "/audit-events";
    if (limit) url += "?limit=" + encodeURIComponent(String(limit));
    return this.fetch(url);
  }
}

